// Generated by tools/recipes.mjs: don't edit by hand. For each clock tempo and way of getting back in time, the
// move that shifts the heading about 10° each way (or turns it round, UT), played with air roll left in the
// third revolution of a clock that starts far right. `result` is what the simulation measured, in degrees.
export const RECIPES = {
  "clock": {
    "jump": {
      "UR": {
        "notch": "Right",
        "circle": 0,
        "hold": 20,
        "result": {
          "right": 4.4,
          "up": 6.1,
          "angle": 7.5
        }
      },
      "UL": {
        "notch": "Lower right",
        "circle": 0,
        "hold": 20,
        "result": {
          "right": -5.2,
          "up": 5.2,
          "angle": 7.4
        }
      },
      "D": {
        "notch": "Up",
        "circle": 0,
        "hold": 26,
        "result": {
          "right": 0.1,
          "up": -10.9,
          "angle": 10.9
        }
      },
      "DR": {
        "notch": "Lower left",
        "circle": 0,
        "hold": 18,
        "result": {
          "right": 6.8,
          "up": -4.8,
          "angle": 8.4
        }
      },
      "UT": {
        "notch": "Up",
        "circle": 0,
        "reverse": 244,
        "result": {
          "right": 161.4,
          "up": 2.1,
          "angle": 161.3
        }
      }
    },
    "catch": {
      "U": {
        "notch": "Left",
        "circle": 0,
        "hold": 22,
        "result": {
          "right": -0.1,
          "up": 11.9,
          "angle": 11.9
        }
      },
      "DL": {
        "notch": "Lower right",
        "circle": 0,
        "hold": 34,
        "result": {
          "right": -5.3,
          "up": -6.2,
          "angle": 8.2
        }
      },
      "D": {
        "notch": "Down",
        "circle": 0,
        "hold": 18,
        "result": {
          "right": 0.5,
          "up": -8.7,
          "angle": 8.7
        }
      },
      "DR": {
        "notch": "Lower left",
        "circle": 0,
        "hold": 14,
        "result": {
          "right": 6.4,
          "up": -4,
          "angle": 7.5
        }
      },
      "UT": {
        "notch": "Upper right",
        "circle": 0,
        "reverse": 328,
        "result": {
          "right": 158.3,
          "up": -36.6,
          "angle": 138.2
        }
      }
    }
  },
  "double": {
    "jump": {
      "R": {
        "notch": "Down",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 7.4,
          "up": 1.1,
          "angle": 7.5
        }
      },
      "UR": {
        "notch": "Right",
        "circle": 0,
        "hold": 16,
        "result": {
          "right": 7,
          "up": 6.5,
          "angle": 9.5
        }
      },
      "U": {
        "notch": "Up",
        "circle": 0,
        "hold": 14,
        "result": {
          "right": -1.2,
          "up": 7.6,
          "angle": 7.7
        }
      },
      "UL": {
        "notch": "Left",
        "circle": 1,
        "hold": 16,
        "result": {
          "right": -6.2,
          "up": 6.7,
          "angle": 9.1
        }
      },
      "L": {
        "notch": "Down",
        "circle": 0,
        "hold": 14,
        "result": {
          "right": -7.7,
          "up": -1.2,
          "angle": 7.8
        }
      },
      "DL": {
        "notch": "Right",
        "circle": 1,
        "hold": 16,
        "result": {
          "right": -6.8,
          "up": -6.3,
          "angle": 9.2
        }
      },
      "D": {
        "notch": "Up",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 1.1,
          "up": -7.2,
          "angle": 7.3
        }
      },
      "DR": {
        "notch": "Left",
        "circle": 0,
        "hold": 16,
        "result": {
          "right": 6.4,
          "up": -6.8,
          "angle": 9.4
        }
      },
      "UT": {
        "notch": "Up",
        "circle": 0,
        "reverse": 208,
        "result": {
          "right": -152.1,
          "up": -5.2,
          "angle": 151.6
        }
      }
    },
    "catch": {
      "R": {
        "notch": "Lower right",
        "circle": 1,
        "hold": 22,
        "result": {
          "right": 12,
          "up": 0.8,
          "angle": 12
        }
      },
      "UR": {
        "notch": "Right",
        "circle": 0,
        "hold": 12,
        "result": {
          "right": 5.1,
          "up": 5.6,
          "angle": 7.6
        }
      },
      "U": {
        "notch": "Upper left",
        "circle": 0,
        "hold": 22,
        "result": {
          "right": 0.1,
          "up": 11.8,
          "angle": 11.8
        }
      },
      "UL": {
        "notch": "Left",
        "circle": 1,
        "hold": 12,
        "result": {
          "right": -5.2,
          "up": 4.9,
          "angle": 7.1
        }
      },
      "L": {
        "notch": "Lower right",
        "circle": 0,
        "hold": 22,
        "result": {
          "right": -11.8,
          "up": 0.1,
          "angle": 11.8
        }
      },
      "DL": {
        "notch": "Upper left",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": -5.8,
          "up": -5.6,
          "angle": 8.1
        }
      },
      "D": {
        "notch": "Upper left",
        "circle": 1,
        "hold": 22,
        "result": {
          "right": 0.7,
          "up": -12,
          "angle": 12
        }
      },
      "DR": {
        "notch": "Lower right",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 5.8,
          "up": -5.8,
          "angle": 8.2
        }
      },
      "UT": {
        "notch": "Up",
        "circle": 0,
        "reverse": 216,
        "result": {
          "right": -153.6,
          "up": -13.2,
          "angle": 150.7
        }
      }
    }
  },
  "triple": {
    "jump": {
      "R": {
        "notch": "Lower right",
        "circle": 2,
        "hold": 16,
        "result": {
          "right": 10.5,
          "up": -0.2,
          "angle": 10.5
        }
      },
      "UR": {
        "notch": "Left",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 7.1,
          "up": 6.9,
          "angle": 9.9
        }
      },
      "U": {
        "notch": "Upper right",
        "circle": 0,
        "hold": 10,
        "result": {
          "right": -0.4,
          "up": 8,
          "angle": 8
        }
      },
      "UL": {
        "notch": "Upper left",
        "circle": 1,
        "hold": 18,
        "result": {
          "right": -8.6,
          "up": 9.5,
          "angle": 12.8
        }
      },
      "L": {
        "notch": "Up",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": -11.1,
          "up": -0.1,
          "angle": 11.1
        }
      },
      "DL": {
        "notch": "Upper right",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": -8.9,
          "up": -8.9,
          "angle": 12.5
        }
      },
      "D": {
        "notch": "Left",
        "circle": 0,
        "hold": 12,
        "result": {
          "right": 1,
          "up": -8.1,
          "angle": 8.1
        }
      },
      "DR": {
        "notch": "Up",
        "circle": 2,
        "hold": 14,
        "result": {
          "right": 6.9,
          "up": -10.2,
          "angle": 12.3
        }
      },
      "UT": {
        "notch": "Down",
        "circle": 2,
        "reverse": 196,
        "result": {
          "right": -160.8,
          "up": 21,
          "angle": 151.8
        }
      }
    },
    "catch": {
      "R": {
        "notch": "Lower left",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 12,
          "up": 0.7,
          "angle": 12
        }
      },
      "UR": {
        "notch": "Lower right",
        "circle": 2,
        "hold": 18,
        "result": {
          "right": 7.8,
          "up": 8.1,
          "angle": 11.2
        }
      },
      "U": {
        "notch": "Right",
        "circle": 0,
        "hold": 18,
        "result": {
          "right": -0.4,
          "up": 8.6,
          "angle": 8.6
        }
      },
      "UL": {
        "notch": "Lower left",
        "circle": 2,
        "hold": 18,
        "result": {
          "right": -8.8,
          "up": 8.9,
          "angle": 12.5
        }
      },
      "L": {
        "notch": "Up",
        "circle": 1,
        "hold": 10,
        "result": {
          "right": -7.9,
          "up": -0.1,
          "angle": 7.9
        }
      },
      "DL": {
        "notch": "Lower left",
        "circle": 0,
        "hold": 10,
        "result": {
          "right": -6.2,
          "up": -6,
          "angle": 8.6
        }
      },
      "D": {
        "notch": "Upper left",
        "circle": 2,
        "hold": 14,
        "result": {
          "right": -0.3,
          "up": -9.7,
          "angle": 9.7
        }
      },
      "DR": {
        "notch": "Down",
        "circle": 1,
        "hold": 12,
        "result": {
          "right": 8.1,
          "up": -8.1,
          "angle": 11.4
        }
      },
      "UT": {
        "notch": "Up",
        "circle": 0,
        "reverse": 204,
        "result": {
          "right": -157.9,
          "up": 22.2,
          "angle": 149.1
        }
      }
    }
  }
};
