// Generated by tools/recipes.mjs: don't edit by hand. For each clock tempo and way of getting back in time, the
// move that shifts the heading about 10° each way (or turns it round, UT), played as the first move of a combo
// (air roll left, a clock from far right, after one revolution to spin up). `result` is what the page measures for
// it, in degrees.
export const RECIPES = {
  "clock": {
    "jump": {
      "UR": {
        "notch": "Left",
        "circle": 0,
        "hold": 20,
        "result": {
          "right": 4.5,
          "up": 5.4,
          "angle": 7.1
        }
      },
      "UL": {
        "notch": "Upper left",
        "circle": 0,
        "hold": 22,
        "result": {
          "right": -5.1,
          "up": 5.8,
          "angle": 7.7
        }
      },
      "D": {
        "notch": "Up",
        "circle": 0,
        "hold": 28,
        "result": {
          "right": -1,
          "up": -12.2,
          "angle": 12.2
        }
      },
      "DR": {
        "notch": "Lower left",
        "circle": 0,
        "hold": 18,
        "result": {
          "right": 4.5,
          "up": -5.7,
          "angle": 7.2
        }
      },
      "UT": {
        "notch": "Right",
        "circle": 0,
        "reverse": 156,
        "result": {
          "right": 161.1,
          "up": 37.2,
          "angle": 138.9
        }
      }
    },
    "catch": {
      "UR": {
        "notch": "Left",
        "circle": 0,
        "hold": 16,
        "result": {
          "right": 3.7,
          "up": 6,
          "angle": 7.1
        }
      },
      "U": {
        "notch": "Left",
        "circle": 0,
        "hold": 24,
        "result": {
          "right": 1.5,
          "up": 12.9,
          "angle": 12.9
        }
      },
      "DL": {
        "notch": "Lower right",
        "circle": 0,
        "hold": 36,
        "result": {
          "right": -3.6,
          "up": -6.2,
          "angle": 7.1
        }
      },
      "D": {
        "notch": "Up",
        "circle": 0,
        "hold": 20,
        "result": {
          "right": 0.3,
          "up": -10.5,
          "angle": 10.5
        }
      },
      "UT": {
        "notch": "Upper right",
        "circle": 0,
        "reverse": 328,
        "result": {
          "right": 161.3,
          "up": -35.2,
          "angle": 140.7
        }
      }
    }
  },
  "double": {
    "jump": {
      "R": {
        "notch": "Down",
        "circle": 1,
        "hold": 16,
        "result": {
          "right": 8.7,
          "up": 2,
          "angle": 9
        }
      },
      "L": {
        "notch": "Down",
        "circle": 0,
        "hold": 14,
        "result": {
          "right": -7.1,
          "up": -0.7,
          "angle": 7.1
        }
      },
      "U": {
        "notch": "Up",
        "circle": 0,
        "hold": 16,
        "result": {
          "right": -2,
          "up": 8.9,
          "angle": 9.1
        }
      },
      "D": {
        "notch": "Up",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 1.2,
          "up": -7.6,
          "angle": 7.7
        }
      },
      "UR": {
        "notch": "Right",
        "circle": 0,
        "hold": 18,
        "result": {
          "right": 7.6,
          "up": 7.7,
          "angle": 10.8
        }
      },
      "DL": {
        "notch": "Right",
        "circle": 1,
        "hold": 18,
        "result": {
          "right": -7.3,
          "up": -7.5,
          "angle": 10.5
        }
      },
      "UL": {
        "notch": "Left",
        "circle": 1,
        "hold": 16,
        "result": {
          "right": -6.4,
          "up": 6.9,
          "angle": 9.4
        }
      },
      "DR": {
        "notch": "Left",
        "circle": 0,
        "hold": 18,
        "result": {
          "right": 7.6,
          "up": -7.3,
          "angle": 10.6
        }
      },
      "UT": {
        "notch": "Up",
        "circle": 1,
        "reverse": 208,
        "result": {
          "right": 152.5,
          "up": 5,
          "angle": 152.1
        }
      }
    },
    "catch": {
      "R": {
        "notch": "Left",
        "circle": 0,
        "hold": 22,
        "result": {
          "right": 11.1,
          "up": -0.3,
          "angle": 11.1
        }
      },
      "L": {
        "notch": "Left",
        "circle": 1,
        "hold": 22,
        "result": {
          "right": -10.9,
          "up": -0.3,
          "angle": 10.9
        }
      },
      "U": {
        "notch": "Right",
        "circle": 0,
        "hold": 22,
        "result": {
          "right": 0.4,
          "up": 11.1,
          "angle": 11.1
        }
      },
      "D": {
        "notch": "Right",
        "circle": 1,
        "hold": 22,
        "result": {
          "right": -0.3,
          "up": -11.1,
          "angle": 11.1
        }
      },
      "UR": {
        "notch": "Right",
        "circle": 0,
        "hold": 12,
        "result": {
          "right": 5.2,
          "up": 4.8,
          "angle": 7.1
        }
      },
      "DL": {
        "notch": "Right",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": -5.2,
          "up": -6.8,
          "angle": 8.5
        }
      },
      "UL": {
        "notch": "Left",
        "circle": 1,
        "hold": 12,
        "result": {
          "right": -5.6,
          "up": 5.1,
          "angle": 7.6
        }
      },
      "DR": {
        "notch": "Left",
        "circle": 0,
        "hold": 14,
        "result": {
          "right": 6.9,
          "up": -5.1,
          "angle": 8.6
        }
      },
      "UT": {
        "notch": "Up",
        "circle": 0,
        "reverse": 216,
        "result": {
          "right": -152.7,
          "up": -11.9,
          "angle": 150.4
        }
      }
    }
  },
  "triple": {
    "jump": {
      "R": {
        "notch": "Lower right",
        "circle": 2,
        "hold": 16,
        "result": {
          "right": 10.6,
          "up": 0,
          "angle": 10.6
        }
      },
      "UR": {
        "notch": "Left",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 7.2,
          "up": 7.1,
          "angle": 10.1
        }
      },
      "U": {
        "notch": "Upper right",
        "circle": 0,
        "hold": 10,
        "result": {
          "right": 0,
          "up": 7.2,
          "angle": 7.2
        }
      },
      "UL": {
        "notch": "Upper left",
        "circle": 1,
        "hold": 18,
        "result": {
          "right": -7.4,
          "up": 9.4,
          "angle": 11.9
        }
      },
      "L": {
        "notch": "Down",
        "circle": 0,
        "hold": 14,
        "result": {
          "right": -11.1,
          "up": 0,
          "angle": 11.1
        }
      },
      "DL": {
        "notch": "Lower left",
        "circle": 0,
        "hold": 14,
        "result": {
          "right": -9,
          "up": -8.7,
          "angle": 12.5
        }
      },
      "D": {
        "notch": "Left",
        "circle": 0,
        "hold": 12,
        "result": {
          "right": 0.4,
          "up": -7.4,
          "angle": 7.4
        }
      },
      "DR": {
        "notch": "Up",
        "circle": 2,
        "hold": 14,
        "result": {
          "right": 5.8,
          "up": -9.6,
          "angle": 11.2
        }
      },
      "UT": {
        "notch": "Down",
        "circle": 2,
        "reverse": 196,
        "result": {
          "right": -162.1,
          "up": 21.7,
          "angle": 152.1
        }
      }
    },
    "catch": {
      "R": {
        "notch": "Lower left",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": 12.1,
          "up": 0.7,
          "angle": 12.1
        }
      },
      "UR": {
        "notch": "Lower right",
        "circle": 2,
        "hold": 18,
        "result": {
          "right": 7.9,
          "up": 7.9,
          "angle": 11.1
        }
      },
      "U": {
        "notch": "Right",
        "circle": 0,
        "hold": 18,
        "result": {
          "right": -0.1,
          "up": 8.5,
          "angle": 8.5
        }
      },
      "UL": {
        "notch": "Lower left",
        "circle": 2,
        "hold": 18,
        "result": {
          "right": -8.5,
          "up": 9.3,
          "angle": 12.6
        }
      },
      "L": {
        "notch": "Down",
        "circle": 0,
        "hold": 10,
        "result": {
          "right": -8.1,
          "up": -0.1,
          "angle": 8.1
        }
      },
      "DL": {
        "notch": "Lower left",
        "circle": 0,
        "hold": 10,
        "result": {
          "right": -6.3,
          "up": -6.4,
          "angle": 9
        }
      },
      "D": {
        "notch": "Lower right",
        "circle": 1,
        "hold": 14,
        "result": {
          "right": -0.4,
          "up": -9.6,
          "angle": 9.6
        }
      },
      "DR": {
        "notch": "Up",
        "circle": 2,
        "hold": 12,
        "result": {
          "right": 7.3,
          "up": -8,
          "angle": 10.8
        }
      },
      "UT": {
        "notch": "Up",
        "circle": 0,
        "reverse": 204,
        "result": {
          "right": -158,
          "up": 21.6,
          "angle": 149.5
        }
      }
    }
  }
};
